config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "movies#home"
  resources :users
  resources :movies, only: [:index, :show]
  resources :netflix
  resources :amazon
  resources :hulu
  resources :hbo
  get 'movies/index', to: 'movies#index'

  post 'movies/index', to: 'movies#searchAPI'

  post 'search', to: 'movies#searchAPI'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guidebox.rb
class Guidebox

  def searchAPI
    userinput = params[:userinput]
    userinput = userinput.split(' ').join('-')
    guidebox_request = HTTParty.get("http://api-public.guidebox.com/v2/search?api_key=a24ffa38333a5845bfaee4f28cece621f4d51c93&type=movie&field=title&query=#{userinput}")
    @movie_info = guidebox_request["results"].first
    # @trailer = guidebox_request["results"]["trailers"]
    @movie_info

  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  validates :username, uniqueness: true
  validates :email, uniqueness: true


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      where(conditions).where(["username = :value OR
                               lower(email) = lower(:value)",
                               { value: login }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/amazon_controller.rb
class AmazonController < ApplicationController
  def index
    @movies = Movie.all
    @user = current_user
  end

  def show
    @movie = Movie.find(params[:id])
    @user = current_user
  end
end

app/controllers/api/v1/discussions_controller.rb
class Api::V1::DiscussionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :destory, :update]

  def new
    @discussion = Discussion.new
  end

  def create
    discussion = Discussion.new(discussion_params)
    group = Group.find(discussion_params['group_id'])
    discussion.user = current_user
    if discussion.save
      flash[:notice] = "Post added successfully"
      discussion_to_send = {}
      discussion_to_send[:id] = discussion.id
      discussion_to_send[:title] = discussion.title
      discussion_to_send[:description] = discussion.description
      discussion_to_send[:created_at] = discussion.created_at
      render json: {
       status: 201,
       message: ("successfully created a post"),
       discussion: discussion_to_send
      }.to_json
    else
      render json: {
        status: 500,
        error: discussion.errors
      }.to_json
    end
  end

  private

  def discussion_params
    params.require(:discussion).permit(:title, :description, :group_id)
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def show
    @discussions = []
    Group.find(params[:id]).discussions.each do |discussion|
      discussion_to_send = {}
      discussion_to_send[:id] = discussion.id
      discussion_to_send[:title] = discussion.title
      discussion_to_send[:description] = discussion.description
      discussion_to_send[:rating] = discussion.rating
      @discussions << discussion_to_send
    end
    render json: { discussions: @discussions }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
                                                       :username, :avatar])
  end
end

app/controllers/hbo_controller.rb
class HboController < ApplicationController
  def index
    @movies = Movie.all
    @user = current_user
  end

  def show
    @movie = Movie.find(params[:id])
    @user = current_user
  end
end

app/controllers/hulu_controller.rb
class HuluController < ApplicationController
  def index
    @movies = Movie.all
    @user = current_user
  end

  def show
    @movie = Movie.find(params[:id])
    @user = current_user
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @user = current_user
  end

  def show
    @movie = Movie.find(params[:id])
    @user = current_user
  end

  def searchAPI
    @movies = Movie.all
    userinput = params[:userinput]
    userinput = userinput.split(' ').join('-')
    response = HTTParty.get("http://api-public.guidebox.com/v2/search?api_key=a24ffa38333a5845bfaee4f28cece621f4d51c93&type=movie&field=title&query=#{userinput}")
    json_response = JSON.parse(response.body)
    json_response["results"].each do |result|
      id = result["id"]
      movie_details = HTTParty.get("http://api-public.guidebox.com/v2/movies/#{id}\?api_key\=a24ffa38333a5845bfaee4f28cece621f4d51c93")
      json_movie_details = JSON.parse(movie_details.body)
      Movie.find_or_create_by!(title: result["title"]) do |movie|
        movie.image_url = result["poster_400x570"]
        movie.description = json_movie_details["overview"]
        movie.premiere_date = json_movie_details["release_date"]
        movie.source = json_movie_details["subscription_web_sources"]
        movie.display_name = json_movie_details["display_name"]
        movie.link = json_movie_details["link"]
      end
  end
  @searched = Movie.where("title ilike ?", "%#{userinput}%")
end
end

app/controllers/netflix_controller.rb
class NetflixController < ApplicationController
  def index
    @movies = Movie.all
    @user = current_user
  end

  def show
    @movie = Movie.find(params[:id])
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Profile picture saved successfully."
      redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email,
                                 :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/amazon/index.html.erb
<hr />
<h2>Amazon Movies</h2>
<div class="row index-row small-up-2 medium-up-3 large-up-4">
<% @movies.each do |movie| %>
  <% if movie.source.present? %>
    <% if movie.source.include?('amazon') %>
    <div class="column column-block">
      <div class"movie-card">
        <div class="overlay-container hvr-curl-top-right">
          <%= link_to image_tag(movie.image_url), movie_path(movie), id: "movie-link" %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/hbo/index.html.erb
<hr />
<h2>HBO Movies</h2>
<div class="row index-row small-up-2 medium-up-3 large-up-4">
<% @movies.each do |movie| %>
  <% if movie.source.present? %>
    <% if movie.source.include?('hbo') %>
    <div class="column column-block">
      <div class"movie-card">
        <div class="overlay-container hvr-curl-top-right">
          <%= link_to image_tag(movie.image_url), movie_path(movie), id: "movie-link" %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/hulu/index.html.erb
<hr />
<h2>Hulu Movies</h2>
<div class="row index-row small-up-2 medium-up-3 large-up-4">
<% @movies.each do |movie| %>
  <% if movie.source.present? %>
    <% if movie.source.include?('hulu') %>
    <div class="column column-block">
      <div class"movie-card">
        <div class="overlay-container hvr-curl-top-right">
          <%= link_to image_tag(movie.image_url), movie_path(movie), id: "movie-link" %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamDirector</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="top-bar-container" data-sticky-container>
      <div class="sticky sticky-topbar" data-sticky data-options="marginTop:0;" style="width:100%">
        <div class="top-bar">
          <div class="top-bar-left">
            <div class="top-bar-title">
              <%= link_to root_path do %>
              <%= image_tag("logo_primary.png", class: "menu-icon") %>
              <% end %>
            </div>
          </div>
          <div class="top-bar-right">
            <ul class="menu">
              <% if current_user %>
              <li class="menu-text" id="size"><%= link_to image_tag("netflix.png"), netflix_index_path  %></li>
              <li class="menu-text" id="size"><%= link_to image_tag("amazon.png"), amazon_index_path  %></li>
              <li class="menu-text" id="size"><%= link_to image_tag("hulu.png"), hulu_index_path %></li>
              <li class="menu-text" id="size"><%= link_to image_tag("hbo.png"), hbo_index_path %></li>
              <li class="menu-text"><%= link_to "Movies", movies_path %></li>
              <li class="menu-text"><%= link_to "Profile", user_path(current_user) %></li>
              <li class="menu-text" id="out"><%= link_to 'Sign out', destroy_user_session_path, method: "delete" %></li>
              <% else %>
              <li class="menu-text" id="size"><%= link_to image_tag("netflix.png"), netflix_index_path  %></li>
              <li class="menu-text" id="size"><%= link_to image_tag("amazon.png"), amazon_index_path  %></li>
              <li class="menu-text" id="size"><%= link_to image_tag("hulu.png"), hulu_index_path %></li>
              <li class="menu-text" id="size"><%= link_to image_tag("hbo.png"), hbo_index_path %></li>
              <li class="menu-text"><%= link_to "Movies", movies_path %></li>
              <li class="menu-text"><%= link_to 'Create Account', new_user_registration_path%></li>
              <li class="menu-text"><%= link_to 'Sign in', new_user_session_path%></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/movies/home.html.erb
<hr />
<div id="background">
</div>

app/views/movies/index.html.erb
<hr />

<div id="search">
  <%= form_tag("/search", method: "post") do %>
    <%= text_field_tag(:userinput) %>
    <%= submit_tag("Search", class: 'position')%>
  <% end %>
</div>
<div class="row index-row small-up-2 medium-up-3 large-up-4">
  <% @movies.each do |movie| %>
  <div class="column column-block">
    <div class"movie-card">
      <div class="overlay-container hvr-curl-top-right">
        <%= link_to image_tag(movie.image_url), movie_path(movie), id: "movie-link" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/movies/searchAPI.html.erb
<hr />
<div id="search">
  <%= form_tag("/search", method: "post") do %>
    <%= text_field_tag(:userinput) %>
    <%= submit_tag("Search", class: 'position')%>
  <% end %>
</div>
<div class="searched">
  <% @searched.each do |movie| %>
          <div class="overlay-container hvr-curl-top-right">
            <%= link_to image_tag(movie.image_url), movie_path(movie), id: "movie-link" %>
          </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div>
  <hr />
  <div class="center">
      <h2><%= @movie.title %></h2>
  </div>
  <div class="center">
    <%= link_to image_tag(@movie.image_url), movie_path(@movie) %>
  </div>
  <div class="center-text">
    <h4>Description</h4>
    <p><%= @movie.description %></p>
  </div>
  <div class="center">
      <% if @movie.source == "[]" || !@movie.source.present? %>
        <h3>Sign up for an email for when this movie is available to stream!</h3>
        <% if current_user %>
          <button class="btn">Email Me!</button>
        <% else %>
          <h5>Sign In Now!</h5>
        <% end %>
      <% else %>
        <h3>This movie available to stream on</h3>
            <% if @movie.source.include?('netflix') %>
                <%= link_to image_tag("netflix.png", class: 'pic') %>
            <% end %>
            <% if @movie.source.include?('amazon') %>
                <%= link_to image_tag("amazon.png", class: 'pic') %>
            <% end %>
            <% if @movie.source.include?('hbo')%>
                <%= link_to image_tag("hbo.png", class: 'pic') %>
            <% end %>
            <% if @movie.source.include?('hulu') %>
                <%= link_to image_tag("hulu.png", class: 'pic') %>
            <% end %>
          <% end %>
    </div>
  </div>

</div>

app/views/netflix/index.html.erb
<hr />
<h2>Netflix Movies</h2>
<div class="row index-row small-up-2 medium-up-3 large-up-4">
<% @movies.each do |movie| %>
  <% if movie.source.present? %>
    <% if movie.source.include?('netflix') %>
    <div class="column column-block">
      <div class"movie-card">
        <div class="overlay-container hvr-curl-top-right">
          <%= link_to image_tag(movie.image_url), movie_path(movie), id: "movie-link" %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Choose or upload profile picture</h1>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :avatar, "Add new photo from file" %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row small-4 columns infopanel">
  <div class="small-12 large-6 columns">
    <div class="row">
      <img src="<%=@user.avatar%>" alt="avatar" class="profile">
    </div>
    <div class="row buttonrow">
      <%= link_to "Edit Profile", edit_user_registration_path, class: "button" %>
      <%= link_to "Change Picture", edit_user_path, class: "button" %>
    </div>
  </div>
  <div class="small-12 large-6 columns">
    <h1><%= @user.first_name %> <%= @user.last_name %>'s Profile</h1>
    <ul class="details">
      <li><strong>Username</strong> <%= @user.username %></li>
      <li><strong>Name</strong> <%= @user.first_name %> <%= @user.last_name %></li>
      <li><strong>Email</strong> <%= @user.email %></li>
    </ul>
  </div>
</div>